CURRICULUM/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('aplicaciones.INDEX.urls')),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

aplicaciones/INDEX/urls.py
from django.urls import path
from .views.views import *
from .views.html.views import *


app_name = 'INICIO'
urlpatterns = [
    #INICIO
    path("",Index.enviar_formulario,name="inicio"),
    path("procesar",Index.procesar_formulario,name="procesar"),
    #HTMLS
    path("mas-trabajos",Html.mas_trabajos,name="mas-trabajos"),
    path("contacto",Html.contacto,name="contacto"),
    path("info",Html.info, name="info"),
]

aplicaciones/INDEX/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime

# Create your models here.

class Entrevistador(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    empresa = models.CharField(max_length=50)
    opinion = models.TextField()
    mejorar = models.TextField()
    fecha = models.DateField(default = datetime.now)

    def __str__(self):
        return f"{self.nombre} {self.apellido} {self.empresa}"

    class Meta:
        verbose_name = 'Entrevistador'
        verbose_name_plural = 'Entrevistadores'
        db_table = 'Entrevistadores'
        ordering = ['fecha']

aplicaciones/INDEX/forms.py
from django import forms
from .models import Entrevistador
#"fecha": forms.DateInput(attrs={"type":"date"})

class FormularioEntrevistador(forms.ModelForm):
    class Meta:
        model = Entrevistador    
        fields='__all__'
        widgets = {
            "nombre": forms.TextInput(attrs={"class":"input1"}),
            "apellido": forms.TextInput(attrs={"class":"input2"}),
            "empresa": forms.TextInput(attrs={"class":"input3"}),
            "fecha": forms.DateInput(attrs={"class":"input4","type":"date"}),
            "opinion": forms.Textarea(attrs={"class":"input5","cols":"30","rows":"10"}),
            "mejorar": forms.Textarea(attrs={"class":"input6"})
            }

aplicaciones/INDEX/views/html/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest, HttpResponse

class Html(HttpRequest):

    def mas_trabajos(request):
        return render(request,"mas-trabajos.html")
    
    def contacto(request):
        return render(request,"contacto.html")

    def info(request):
        return render(request,"info.html")

aplicaciones/INDEX/views/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest, HttpResponse
from aplicaciones.INDEX.forms import FormularioEntrevistador


class Index(HttpRequest):
    def enviar_formulario(request):
        return render(request,"index.html",{
            'form': FormularioEntrevistador()
        })

    def procesar_formulario(request):
        formulario = FormularioEntrevistador(request.POST)
        if formulario.is_valid():
            formulario.save()
            return render(request,"index.html",{
                'form': FormularioEntrevistador(),
                'enviado':"enviado"
            })
        return redirect(to='INICIO:inicio')
    

aplicaciones/INDEX/templates/contacto.html
{% extends 'layout2.html' %}
{% load static %}
        
    {% block head %}   
        <!--SMTPJS MAIL-->
        <script src="https://smtpjs.com/v3/smtp.js"></script>
        <!--SWEET ALERT-->
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
        <!--MY JAVASCRIPT-->
        <script src="{% static 'js/send-mail.js' %}"></script>
        <!--MY CSS-->
        <link href="{% static 'css/contacto.css' %}" rel="stylesheet">
    {% endblock %}


    {% block body %}           
            <div class="mail-container">
                <h1>Enviar email</h1>
                <ul class="form-container">
                    <form onsubmit="return false">
                        <li><label>Nombre: </label><input type="text" placeholder="Nombre" id="nombre" required></li>
                        <li><label>Ingresa tu email: </label><input type="email" placeholder="Email" id="email" required></li>
                        <li><label>Subject: </label><input type="text" placeholder="Subject" id="subject" required></li>
                        <li><label>Mensaje: </label><textarea rows="3" cols="10" placeholder="Mensaje" id="mensaje" required></textarea></li>
                        <li><button type="submit" id="send-mail">Enviar</button></li>
                    </form>
                </ul>
            </div>
    {% endblock %}

aplicaciones/INDEX/templates/index.html
{% extends 'layout.html' %}
{% load static %}

    
    {% block head %}    
        <!--MY CSS-->
        <link rel="stylesheet" href="{% static 'css/inde.css' %}">
        <link rel="stylesheet" href="{% static 'css/formm.css' %}">
        <!--MY JAVASCRIPT-->
        <script src="{% static 'js/slider-portada.js' %}"></script>
        <script src="{% static 'js/formulario-recibido.js' %}"></script>
    {% endblock %}


    {% block body %}
        {% if enviado %}
            <div class="recibido" role="alert"><i class="fas fa-clipboard-check"></i>Formulario recibido
                <li><button id="ok">Ok</button></li>
            </div>
        {% endif %}
        
        <div class="slider-container">      <!--SLIDER-->
            <div>
                <ul class="slider s1">
                    <li>
                        <h1>Mis conocimientos</h1>
                        <p>
                        -Conocimientos en C++, HTML, CSS, JAVASCRIPT
                        , JQUERY, PYTHON POO, DJANGO, MYSQL y WORDPRESS<br>
                        -Estudio en UTN (Universidad Tecnologica Nacional)<br>
                        -Cursos realizado de fullstack HTML, CSS y Javascript 
                        con Django y SQLite.<br>
                        -3 cursos mas realizados de Python POO, Mysql y Wordpress.<br>
                        -Uso de git-hub y git-bash para proyectos.<br>
                        -Ingles avanzado (sin problemas de tener una entrevista en ingles)
                        </p>
                    </li>
                </ul>
                <ul class="slider s2">
                    <li>
                        <h1>Mis objetivos</h1>
                        <p>
                            Uno de mis objetivos es llevar al maximo mis habilidades
                            como desarrollador web mientras termino la facultad, para algun dia 
                            dedicarme a machine learning y big-data.
                        </p>
                    </li>
                </ul>
                <ul class="slider s3">
                    <li>
                        <h1>Mis creencias</h1>
                        <p>
                            Esforzarme al 150% para lograr mis objetivos, 
                            creo que todo se consigue a través del trabajo duro 
                            con dedicacion y pasión por lo que uno hace
                        </p>
                    </li>
                </ul>
            </div>
            <div class="flecha-slider-izquierda flechas-slider">    <!--FLECHAS-->
                <li><i class="fas fa-chevron-left"></i></li>
            </div>
            <div class="flecha-slider-derecha flechas-slider">
                <li><i class="fas fa-chevron-right"></i></li>
            </div>
            <div class="paginacion">                        <!--PAGINACION-->
                <li></li>
                <li></li>
                <li></li>
            </div>
        </div>
        <div class="form-container animacion5" id="encuesta">
            <h1>Encuesta para entrevistadores</h1>     
            <form action="{% url 'INICIO:procesar' %}" method="post">
                {% csrf_token %}        
                <div>
                    {{ form.nombre.label_tag }}
                    {{ form.nombre }}
                    
                    {{ form.apellido.label_tag }}
                    {{ form.apellido }}
                    
                    {{ form.empresa.label_tag }}
                    {{ form.empresa }}
                    
                    {{ form.fecha.label_tag }}
                    {{ form.fecha }}
                </div>
                <div>
                    {{ form.opinion.label_tag }}
                    {{ form.opinion }}
                </div>
                <div>
                    <label for="Puntos a mejorar">Puntos a mejorar:</label>
                    {{ form.mejorar }}
                </div> 
                <ul>
                    <button type="submit" id="form-btn">Enviar</button>
                </ul>
            </form>
        </div>
        <div class="information-container" id="info">           <!--INFO-->
            <div class="first-line">
                <ul class="presentation-text text1 animacion2">             <!-------- animacion 1 -------->
                    <h1>Acerca de Mi</h1>
                    <p>
                        Mi nombre es Walter, tengo 26 años, nacido en Argentina,
                        soy de Buenos Aires vivo en General Pacheco una ciudad de
                        Zona Norte en Tigre. Mis estudios y experiencias se encuentran
                        detalladas por debajo. Me 
                        gustaria tener la oportunidad de formar parte de su equipo,
                        debido a que seria mi primer experiencia y que considero que mis conocimientos
                        son lo suficientes como para formar parte de un equipo envio
                        mi curriculum, me gustaria pedirle humildemente que forme parte de mi encuesta
                        acerca de que piensa sobre mi y mis trabajos para ayudarme a mejorar o 
                        tener en cuenta ciertos aspectos que pueden enriquecerme aun mas como
                        desarrollador, desde ya muchas gracias.
                    </p>
                </ul>
                <ul class="presentation-img img1 animacion1">                              <!-------- animacion 2 -------->
                    <li class="imagen-pagina"><a href="https://walter-damian-diaz.github.io/web_construccion/" target="blank"><img src="{% static 'imagenes/index/6.JPG' %}" alt=""></a></li>
                    <li class="button-img"><a href="https://walter-damian-diaz.github.io/web_constructora/" target="blank"><i class="fas fa-plus"></i>Ver pagina</a></li>
                </ul>
            </div>
            <div class="second-line">
                <ul class="presentation-text text2 animacion3" id="second-text">        <!-------- animacion 1 -------->
                    <h1>Estudios y experencias</h1>
                    <p>
                        Actualmente estudio programacion en UTN (Universidad Tecnologica Nacional)
                        estoy en mi primer año como programador con 5 materias ya aprobadas de el 
                       primer cuatrimestre con promedios de 9 y 10 en todas las materias, en la 
                        facultad hasta el momento usamos C++ como lenguaje, en el cual desarrolle 
                        diferentes tipos de logicas y tambien juegos.
                        Mi dedicacion por aprender me llevaron a meterme en un curso de fullstack
                        con Django, Javascript, Bootstrap, SQLite, CSS Y HTML dictado por Polotic 
                        (Silicon Misiones),de hecho esta pagina la monte en Django con Sqlite para 
                        poder guardar la encuesta en una base de datos. 
                        Tambien realize cursos en Fablab de Python POO y Mysql. Por otra parte tambien 
                        hice un curso de WordPress en mi facultad UTN. Aunque mi experiencia laboral
                        es nula hasta el momento, me gustaria emprender en este camino en el cual coincidero 
                        soy muy dedicado y autodidacta. Tambien entiendo Ingles y puedo hablarlo, sin problemas 
                        de tener una entrevista personal y completamente en ingles.
                    </p>
                </ul>
                <ul class="presentation-img img2 animacion4">                                 <!-------- animacion 2 -------->
                    <li class="imagen-pagina"><a href="https://walter-damian-diaz.github.io/web_ropa/" target="blank"><img src="{% static 'imagenes/index/4.JPG' %}" alt=""></a></li>
                    <li class="button-img"><a href="https://walter-damian-diaz.github.io/web_ropa/" target="blank"><i class="fas fa-plus"></i>  Ver pagina</a></li>
                </ul>
            </div>            
        </div>
        <script src="{% static 'js/animaciones-.js' %}"></script>
    {% endblock %}

aplicaciones/INDEX/templates/info.html
{% extends 'layout2.html' %}
{% load static %}


{% block head %}
        <link rel="stylesheet" href="{% static 'css/info.css' %}">
{% endblock  %}


{% block body %}
            <div class="section-container">
                <div class="titulo-seccion">
                    <h1>Leer</h1>
                    <p>
                        Los trabajos o ejercicios de las clases 
                        estan en mi <a href="https://github.com/Walter-Damian-Diaz">GitHub</a> y en la seccion <a href="{% url 'INICIO:mas-trabajos' %}"> Mas trabajos</a> 
                        . Podes acceder a los ejercicios clickeando sobre las palabras verdes o el menu principal. Saludos
                    </p>
                </div>
                <ul class="django">
                    <li class="textos">
                        <p> <strong>Certificado en:</strong> Fullstack con Django</p>
                        <p><strong>Emitido por:</strong> Polo Tic Silicon Misiones </p>
                    </li>
                    <li class="imagenes">
                        <img src="{% static 'imagenes/certificados/django.JPG' %}" alt="">
                    </li>
                </ul>
                <ul class="wordpress">
                    <li class="textos">
                        <p><strong>Certificado en:</strong> WordPress</p>
                        <p><strong>Emitido por:</strong> UTN (Universidad Tecnologica Nacional)</p>
                    </li>
                    <li class="imagenes">
                        <img src="{% static 'imagenes/certificados/wordpress.JPG' %}" alt="">
                    </li>
                </ul>
                <ul class="python">
                    <li class="textos">
                        <p> <strong>Certificado en:</strong> Python POO</p>
                        <p><strong>Emitido por:</strong> Fablab </p>
                    </li>
                    <li class="imagenes">
                        <img src="{% static 'imagenes/certificados/python.JPG' %}" alt="">
                    </li>
                </ul>
                <ul class="mysql">
                    <li class="textos">
                        <p> <strong>Certificado en:</strong> Mysql </p>
                        <p><strong>Emitido por:</strong> Fablab </p>
                    </li>
                    <li class="imagenes">
                        <img src="{% static 'imagenes/certificados/mysql.JPG' %}" alt="">
                    </li>
                </ul>
            </div>
{% endblock  %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
         <!--ICON-AWSOME-->
         <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
         <!--jQUERY-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <!--MY JAVASCRIPT-->
        <script src="{% static 'js/menu_responsive.js' %}"></script>
        <script src="{% static 'js/intercambiar-textos.js' %}"></script>
         <!--MY CSS-->
        <link href="{% static 'css/header---.css' %}" rel="stylesheet">
        <link href="{% static 'css/footer-.css' %}" rel="stylesheet">
        {% block head %}
        


        {% endblock %}
    </head>
    <body>
        <header>
            <div class="menu-responsive">
                <h1>Menu</h1><i class="fas fa-align-justify iconoMenu"></i><i class="fas fa-times xMenu"></i>
            </div>
            <nav class="menu-principal">             <!--MENU PRINCIPAL-->
                <ul class="nom">
                    <h1>Walter Damian Diaz</h1>
                </ul>
                <ul class="menu">
                    <li><a href="{% url 'INICIO:inicio' %}">Inicio</a></li>
                    <li id="liToggle">
                        <div>
                            <a href="#" class="sin-menu"><i class="fas fa-suitcase"></i>Mas trabajos</a>
                            <i class="fas fa-chevron-down flechaAbajo flechas"></i>
                            <i class="fas fa-chevron-right flechaDerecha flechas"></i>
                        </div>
                        <ul class="sub-menu1">                               <!--SUB-MENU-->
                            <li><a href="{% url 'INICIO:mas-trabajos' %}">Ver trabajos</a></li>
                            <li><a href="#">vacio</a></li>
                            <li><a href="#">vacio</a></li>
                            <li><a href="#">vacio</a></li>
                        </ul>
                    </li>
                    <li>
                        <div>
                            <a href="{% url 'INICIO:info' %}" class="sin-menu"><i class="fas fa-info-circle"></i>Certificados</a>
                        </div>
                    </li>
                    <li>
                        <div>
                            <a href="#ubicacion" class="sin-menu ubicacion-btn"><i class="fas fa-map-marker-alt"></i>Ubicacion</a>
                        </div>
                    </li>
                    <li>
                        <div>
                            <a href="{% url 'INICIO:contacto' %}" class="sin-menu"><i class="fas fa-envelope-open-text"></i>Contacto</a>
                        </div>
                    </li>
                </ul>
            </nav>
            
            {% block header %}


            {% endblock %}

        </header>
        <section>
            <div class="fondo-container">         <!--FONDO-->
                <ul class="fondo-izquierdo">
                    <img src="{% static 'imagenes/logo/1.png' %}" alt="">
                    <p class="dialogo">Soy walter</p>
                </ul>
                <ul class="fondo-derecho">
                    <div>
                        <h1>Hola</h1>
                        <p>
                            Mi nombre es walter, soy de Buenos Aires(Argentina).
                            Bienvenido/a a mi portfolio, debajo se encuentra mi informacion
                            academica, y algunos proyectos, hay mas en la seccion 
                            "mas trabajos", mientras armaba mi porfolio decidi que seria buena idea 
                            implementar una base de datos para guardar una encuesta 
                            que esta dirigida hacia entrevistadores, esta pagina 
                            la monte en Django con Sqlite. Sería de gran ayuda para mi que 
                            completes mi encuesta de como calificarias mi desempeño 
                            como programador, gracias, agradezco tu tiempo. Saludos
                        </p>
                        <div class="iconos-boton">                     <!--ICONOS PORTADA-->
                            <div class="iconos">
                                <a href="https://github.com/Walter-Damian-Diaz?tab=repositories" target="blank"><i class="fab fa-github"></i></a>
                                <a href="https://api.whatsapp.com/send?phone=541161023944" target="blank"><i class="fab fa-whatsapp"></i></a>
                                <a href="{% url 'INICIO:contacto' %}"><i class="fas fa-envelope-open-text"></i></a>
                            </div>                
                            <div class="boton-encuesta">
                                <a href="#encuesta" style="text-decoration:none;">Ver Encuesta</a>
                            </div>
                        </div>
                    </div>
                </ul>
            </div>

            {% block body %}



            {% endblock %}

        </section>
        <footer>
            <div class="mis-trabajos">             <!--MIS TRABAJOS-->
                <h1>Click en el boton para ver mas trabajos</h1>
                <a href="{% url 'INICIO:mas-trabajos' %}">Ver</a>
            </div>
            <div class="ubicacion" id="ubicacion">      <!--MAPA-->
                <h1><i class="fas fa-map-marker-alt"></i>  Ubicacion</h1>
                <p>Lugar donde recido actualmente</p>
                <li id="mapa"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d52639.90161180773!2d-58.69309449800724!3d-34.45230398041936!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bca39ca574d823%3A0xd4fb0a11188d493e!2sGral.%20Pacheco%2C%20Provincia%20de%20Buenos%20Aires!5e0!3m2!1ses-419!2sar!4v1610923020988!5m2!1ses-419!2sar"  width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe></li>
            </div>            
            <div class="footer-container">
                <ul class="logo-footer">
                    <li><img src="{% static 'imagenes/logo/1.png' %}" alt=""></li>
                </ul>
                <ul class="about-footer">
                    <p>Mail: walter.diaz@alumnos.frgp.utn.edu.ar</p>
                    <p>Localidad: Tigre(Gral.Pacheco)</p>
                    <p>Direccion: Tucuman 288</p>
                    <p>Tel: 1161023944</p>
                </ul>
                <ul class="info-footer">
                    <li><a href="{% url 'INICIO:mas-trabajos' %}">Mas trabajos</a></li>
                    <li><a href="{% url 'INICIO:info' %}">Info</a></li>
                    <li><a href="#ubicacion">Ubicacion</a></li>
                    <li><a href="{% url 'INICIO:contacto' %}">Contacto</a></li>
                </ul>
                <ul class="iconos iconos-footer">                 <!--ICONOS FOOTER-->
                    <a href="https://github.com/Walter-Damian-Diaz?tab=repositories" target="blank"><i class="fab fa-github"></i></a>
                    <a href="https://api.whatsapp.com/send?phone=541161023944" target="blank"><i class="fab fa-whatsapp"></i></a>
                    <a href="{% url 'INICIO:contacto' %}"><i class="fas fa-envelope-open-text"></i></a>
                </ul>
            </div>
            <div class="text-bottom">
                <h1>Gracias por visitar mi pagina, espero sea de tu agrado</h1>
            </div>            
            {% block footer %}


            {% endblock %}
        </footer>
    </body>
</html>

templates/layout2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
         <!--ICON-AWSOME-->
         <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
         <!--jQUERY-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <!--MY JAVASCRIPT-->
        <script src="{% static 'js/menu_responsive.js' %}"></script>
        <script src="{% static 'js/intercambiar-textos.js' %}"></script>
         <!--MY CSS-->
        <link href="{% static 'css/header---.css' %}" rel="stylesheet">
        <link href="{% static 'css/footer-.css' %}" rel="stylesheet">
        {% block head %}
        


        {% endblock %}
    </head>
    <body>
        <header>
            <div class="menu-responsive">
                <h1>Menu</h1><i class="fas fa-align-justify iconoMenu"></i><i class="fas fa-times xMenu"></i>
            </div>
            <nav class="menu-principal">             <!--MENU PRINCIPAL-->
                <ul class="nom">
                    <h1>Walter Damian Diaz</h1>
                </ul>
                <ul class="menu">
                    <li><a href="{% url 'INICIO:inicio' %}">Inicio</a></li>
                    <li id="liToggle">
                        <div>
                            <a href="#" class="sin-menu"><i class="fas fa-suitcase"></i>Mas trabajos</a>
                            <i class="fas fa-chevron-down flechaAbajo flechas"></i>
                            <i class="fas fa-chevron-right flechaDerecha flechas"></i>
                        </div>
                        <ul class="sub-menu1">                               <!--SUB-MENU-->
                            <li><a href="{% url 'INICIO:mas-trabajos' %}">Ver trabajos</a></li>
                            <li><a href="#">vacio</a></li>
                            <li><a href="#">vacio</a></li>
                            <li><a href="#">vacio</a></li>
                        </ul>
                    </li>
                    <li>
                        <div>
                            <a href="{% url 'INICIO:info' %}" class="sin-menu"><i class="fas fa-info-circle"></i>Certificados</a>
                        </div>
                    </li>
                    <li>
                        <div>
                            <a href="#ubicacion" class="sin-menu ubicacion-btn"><i class="fas fa-map-marker-alt"></i>Ubicacion</a>
                        </div>
                    </li>
                    <li>
                        <div>
                            <a href="{% url 'INICIO:contacto' %}" class="sin-menu"><i class="fas fa-envelope-open-text"></i>Contacto</a>
                        </div>
                    </li>
                </ul>
            </nav>
            
            {% block header %}


            {% endblock %}

        </header>
        <section>
            <div class="fondo-container">         <!--FONDO-->
                <ul class="fondo-izquierdo">
                    <img src="{% static 'imagenes/logo/1.png' %}" alt="">
                    <p class="dialogo">Soy walter</p>
                </ul>
                <ul class="fondo-derecho">
                    <div>
                        <h1>Hola</h1>
                        <p>
                            Mi nombre es walter, soy de Buenos Aires(Argentina).
                            Bienvenido/a a mi portfolio, debajo se encuentra mi informacion
                            academica, y algunos proyectos, hay mas en la seccion 
                            "mas trabajos", mientras armaba mi porfolio decidi que seria buena idea 
                            implementar una base de datos para guardar una encuesta 
                            que esta dirigida hacia entrevistadores, esta pagina 
                            la monte en Django con Sqlite. Sería de gran ayuda para mi que 
                            completes mi encuesta de como calificarias mi desempeño 
                            como programador, gracias, agradezco tu tiempo. Saludos
                        </p>
                        <div class="iconos-boton">                     <!--ICONOS PORTADA-->
                            <div class="iconos">
                                <a href="https://github.com/Walter-Damian-Diaz?tab=repositories" target="blank"><i class="fab fa-github"></i></a>
                                <a href="https://api.whatsapp.com/send?phone=541161023944" target="blank"><i class="fab fa-whatsapp"></i></a>
                                <a href="{% url 'INICIO:contacto' %}"><i class="fas fa-envelope-open-text"></i></a>
                            </div>                
                        </div>
                    </div>
                </ul>
            </div>

            {% block body %}



            {% endblock %}
            
        </section>
        <footer>
            <div class="mis-trabajos">             <!--MIS TRABAJOS-->
                <h1>Click en el boton para ver mas trabajos</h1>
                <a href="{% url 'INICIO:mas-trabajos' %}">Ver</a>
            </div>
            <div class="ubicacion" id="ubicacion">      <!--MAPA-->
                <h1><i class="fas fa-map-marker-alt"></i>  Ubicacion</h1>
                <p>Lugar donde recido actualmente</p>
                <li id="mapa"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d52639.90161180773!2d-58.69309449800724!3d-34.45230398041936!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bca39ca574d823%3A0xd4fb0a11188d493e!2sGral.%20Pacheco%2C%20Provincia%20de%20Buenos%20Aires!5e0!3m2!1ses-419!2sar!4v1610923020988!5m2!1ses-419!2sar"  width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe></li>
            </div>            
            <div class="footer-container">
                <ul class="logo-footer">
                    <li><img src="{% static 'imagenes/logo/1.png' %}" alt=""></li>
                </ul>
                <ul class="about-footer">
                    <p>Mail: walter.diaz@alumnos.frgp.utn.edu.ar</p>
                    <p>Localidad: Tigre(Gral.Pacheco)</p>
                    <p>Direccion: Tucuman 288</p>
                    <p>Tel: 1161023944</p>
                </ul>
                <ul class="info-footer">
                    <li><a href="{% url 'INICIO:mas-trabajos' %}">Mas trabajos</a></li>
                    <li><a href="{% url 'INICIO:info' %}">Info</a></li>
                    <li><a href="#ubicacion">Ubicacion</a></li>
                    <li><a href="{% url 'INICIO:contacto' %}">Contacto</a></li>
                </ul>
                <ul class="iconos iconos-footer">                 <!--ICONOS FOOTER-->
                    <a href="https://github.com/Walter-Damian-Diaz?tab=repositories" target="blank"><i class="fab fa-github"></i></a>
                    <a href="https://api.whatsapp.com/send?phone=541161023944" target="blank"><i class="fab fa-whatsapp"></i></a>
                    <a href="{% url 'INICIO:contacto' %}"><i class="fas fa-envelope-open-text"></i></a>
                </ul>
            </div>
            <div class="text-bottom">
                <h1>Gracias por visitar mi pagina, espero sea de tu agrado</h1>
            </div>            
            {% block footer %}


            {% endblock %}
        </footer>
    </body>
</html>